#!/bin/bash

python generate_stats.py --csvs "Bun_JS=../dataset/fibonacci/Bun_.1.2.16_fibonacci.csv" "Bun_WASM=../dataset/fibonacci/Bun_WASM.1.2.16_fibonacci.csv" "Deno_JS=../dataset/fibonacci/Deno_.2.3.6_fibonacci.csv" "Deno_Rust=../dataset/fibonacci/Deno_Rust.2.3.6_fibonacci.csv" "Deno_WASM=../dataset/fibonacci/Deno_WASM.2.3.6_fibonacci.csv" "Node_JS=../dataset/fibonacci/Node_.22.16.0_fibonacci.csv" "Node_C++=../dataset/fibonacci/Node_C++.22.16.0_fibonacci.csv" "Node_WASM=../dataset/fibonacci/Node_WASM.22.16.0_fibonacci.csv" "Chrome_JS=../dataset/fibonacci/Chrome_.137.0.0.0_fibonacci.csv" "Chrome_WASM=../dataset/fibonacci/Chrome_WASM.137.0.0.0_fibonacci.csv" "Firefox_JS=../dataset/fibonacci/Firefox_.138.0_fibonacci.csv" "Firefox_WASM=../dataset/fibonacci/Firefox_WASM.138.0_fibonacci.csv" --out ../stats/fibonacci_stats.json

python generate_stats.py --csvs "Bun_JS=../dataset/linearSearch/Bun_.1.2.16_linearSearch.csv" "Bun_WASM=../dataset/linearSearch/Bun_WASM.1.2.16_linearSearch.csv" "Deno_JS=../dataset/linearSearch/Deno_.2.3.6_linearSearch.csv" "Deno_Rust=../dataset/linearSearch/Deno_Rust.2.3.6_linearSearch.csv" "Deno_WASM=../dataset/linearSearch/Deno_WASM.2.3.6_linearSearch.csv" "Node_JS=../dataset/linearSearch/Node_.22.16.0_linearSearch.csv" "Node_C++=../dataset/linearSearch/Node_C++.22.16.0_linearSearch.csv" "Node_WASM=../dataset/linearSearch/Node_WASM.22.16.0_linearSearch.csv" "Chrome_JS=../dataset/linearSearch/Chrome_.137.0.0.0_linearSearch.csv" "Chrome_WASM=../dataset/linearSearch/Chrome_WASM.137.0.0.0_linearSearch.csv" "Firefox_JS=../dataset/linearSearch/Firefox_.138.0_linearSearch.csv" "Firefox_WASM=../dataset/linearSearch/Firefox_WASM.138.0_linearSearch.csv" --out ../stats/linealSearch_stats.json

python generate_stats.py --csvs "Bun_JS=../dataset/binarySearch/Bun_.1.2.16_binarySearch.csv" "Bun_WASM=../dataset/binarySearch/Bun_WASM.1.2.16_binarySearch.csv" "Deno_JS=../dataset/binarySearch/Deno_.2.3.6_binarySearch.csv" "Deno_Rust=../dataset/binarySearch/Deno_Rust.2.3.6_binarySearch.csv" "Deno_WASM=../dataset/binarySearch/Deno_WASM.2.3.6_binarySearch.csv" "Node_JS=../dataset/binarySearch/Node_.22.16.0_binarySearch.csv" "Node_C++=../dataset/binarySearch/Node_C++.22.16.0_binarySearch.csv" "Node_WASM=../dataset/binarySearch/Node_WASM.22.16.0_binarySearch.csv" "Chrome_JS=../dataset/binarySearch/Chrome_.137.0.0.0_binarySearch.csv" "Chrome_WASM=../dataset/binarySearch/Chrome_WASM.137.0.0.0_binarySearch.csv" "Firefox_JS=../dataset/binarySearch/Firefox_.138.0_binarySearch.csv" "Firefox_WASM=../dataset/binarySearch/Firefox_WASM.138.0_binarySearch.csv" --out ../stats/binarySearch_stats.json

python generate_stats.py --csvs "Bun_JS=../dataset/bubbleSort/Bun_.1.2.16_bubbleSort.csv" "Bun_WASM=../dataset/bubbleSort/Bun_WASM.1.2.16_bubbleSort.csv" "Deno_JS=../dataset/bubbleSort/Deno_.2.3.6_bubbleSort.csv" "Deno_Rust=../dataset/bubbleSort/Deno_Rust.2.3.6_bubbleSort.csv" "Deno_WASM=../dataset/bubbleSort/Deno_WASM.2.3.6_bubbleSort.csv" "Node_JS=../dataset/bubbleSort/Node_.22.16.0_bubbleSort.csv" "Node_C++=../dataset/bubbleSort/Node_C++.22.16.0_bubbleSort.csv" "Node_WASM=../dataset/bubbleSort/Node_WASM.22.16.0_bubbleSort.csv" "Chrome_JS=../dataset/bubbleSort/Chrome_.137.0.0.0_bubbleSort.csv" "Chrome_WASM=../dataset/bubbleSort/Chrome_WASM.137.0.0.0_bubbleSort.csv" "Firefox_JS=../dataset/bubbleSort/Firefox_.138.0_bubbleSort.csv" "Firefox_WASM=../dataset/bubbleSort/Firefox_WASM.138.0_bubbleSort.csv"  --out ../stats/bubbleSort_stats.json

python generate_stats.py --csvs "Bun_JS=../dataset/queue/Bun_.1.2.16_queue.csv" "Bun_WASM=../dataset/queue/Bun_WASM.1.2.16_queue.csv" "Deno_JS=../dataset/queue/Deno_.2.3.6_queue.csv" "Deno_Rust=../dataset/queue/Deno_Rust.2.3.6_queue.csv" "Node_JS=../dataset/queue/Node_.22.16.0_queue.csv" "Node_C++=../dataset/queue/Node_C++.22.16.0_queue.csv" "Node_WASM=../dataset/queue/Node_WASM.22.16.0_queue.csv" "Chrome_JS=../dataset/queue/Chrome_.137.0.0.0_queue.csv" "Chrome_WASM=../dataset/queue/Chrome_WASM.137.0.0.0_queue.csv" "Firefox_JS=../dataset/queue/Firefox_.138.0_queue.csv" "Firefox_WASM=../dataset/queue/Firefox_WASM.138.0_queue.csv" --out ../stats/queue_stats.json